---
- name: Install node dependencies
  yum:
    name:
      - libpng
      - libpng-devel
      - libpng12
      - libpng12-devel
      - gcc-c++
      - make
      - kernel-devel
    state: latest
  become: yes
