---
- name: Install gulp
  npm:
    name: gulp
    version: "{{ gulp_version }}"
  global: yes
  when: install_gulp

- name: Install bower
  npm:
    name: bower
    version: "{{ bower_version }}"
  global: yes
  when: install_bower
