---
- include_tasks: nvm.yml
- include_tasks: node-loop.yml
  when: "{{ node_versions }}"

- name: Set nvm alias default
  shell: source ~/.nvm/nvm.sh && nvm set alias default "{{ node_alias_default }}"
  when: node_alias_default == 'lts/*' or (node_alias_default in node_versions and node_alias_default != '--lts')

- include_tasks: dependencies.yml
- include_tasks: global-node-packages.yml
